name: Send GitHub Issue to Coda

on:
  issues:
    types: [opened]

jobs:
  send-to-coda:
    runs-on: ubuntu-latest
    steps:
      - name: Send data to Coda
        run: |
          curl -X POST "https://coda.io/apis/v1/docs/Nsl232iyRb/hooks/automation/grid-auto-51gLpAnnjK" \
          -H "Authorization: Bearer ${{ secrets.CODA_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "rows": [
              {
                "cells": [
                  { "column": "c-IssueTitle", "value": "${{ github.event.issue.title }}" },
                  { "column": "c-IssueURL", "value": "${{ github.event.issue.html_url }}" },
                  { "column": "c-State", "value": "${{ github.event.issue.state }}" }
                ]
              }
            ]
          }'
